services:
  - type: web
    name: heltec-thermo-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
